name: Validate HACS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@22.5.0
        with:
          category: integration